In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

## Layers without Parameters

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-09, grad_fn=<MeanBackward0>)

## Layers with Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.8615,  0.4974, -0.1062],
        [ 0.0160, -0.5411, -1.1357],
        [ 0.1630,  0.4322, -0.0153],
        [ 1.5558,  0.9848, -0.0581],
        [ 0.8916,  0.2426, -0.1147]], requires_grad=True)

In [8]:
linear(torch.rand(2, 5))

tensor([[1.9398, 2.5110, 0.0000],
        [1.1591, 1.8751, 0.0000]])

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[8.9927],
        [8.1632]])